"""'init db'

Revision ID: d6d3b53e2821
Revises: 
Create Date: 2022-07-18 14:58:36.585599

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd6d3b53e2821'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('co_countries',
    sa.Column('iso', mysql.CHAR(length=2), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('iso3', mysql.CHAR(length=3), nullable=True),
    sa.Column('available', mysql.TINYINT(display_width=1), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('iso')
    )
    op.create_table('co_languages',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('code', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=5), nullable=False),
    sa.Column('language', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=30), nullable=False),
    sa.Column('available', mysql.TINYINT(display_width=1), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('config_permissions',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('label', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config_roles',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('label', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config_tag_types',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('label', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('co_addresses',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('streetAndNumber', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('country', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('zip', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['country'], ['co_countries.iso'], name='co_addresses_country_fk', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config_role_has_permissions',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('roleId', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('permissionId', mysql.INTEGER(display_width=11), nullable=False),
    sa.ForeignKeyConstraint(['permissionId'], ['config_permissions.id'], name='config_role_has_permissions_permissionId_fk', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['roleId'], ['config_roles.id'], name='config_role_has_permissions_roleId_fk', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config_tags',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('label', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('tagTypeId', mysql.INTEGER(display_width=11), nullable=False),
    sa.ForeignKeyConstraint(['tagTypeId'], ['config_tag_types.id'], name='config_tags_tagTypeId_fk', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('a_users',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('uuid', mysql.CHAR(length=36), server_default=sa.text('(UUID())'), nullable=False),
    sa.Column('uniqueId', mysql.VARCHAR(length=8), nullable=False),
    sa.Column('fullName', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('addressId', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('interfaceLanguageCode', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=5), server_default=sa.text("'fr'"), nullable=False),
    sa.Column('createdAt', mysql.DATETIME(), nullable=True),
    sa.Column('updatedAt', mysql.DATETIME(), nullable=True),
    sa.Column('deletedAt', mysql.DATETIME(), nullable=True),
    sa.Column('updatedPasswordAt', mysql.DATETIME(), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('isActive', mysql.TINYINT(display_width=1), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['addressId'], ['co_addresses.id'], name='a_users_addressId_fk', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interfaceLanguageCode'], ['co_languages.code'], name='a_users_interfaceLanguageCode_fk', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uniqueId'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('a_users_roles',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('userId', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('roleId', mysql.INTEGER(display_width=11), nullable=False),
    sa.ForeignKeyConstraint(['roleId'], ['config_roles.id'], name='a_users_roles_roleId_fk', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['a_users.id'], name='a_users_roles_userId_fk', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('a_users_tags',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('userId', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('tagId', mysql.INTEGER(display_width=11), nullable=False),
    sa.ForeignKeyConstraint(['tagId'], ['config_tags.id'], name='a_users_tags_tagId_fk', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['a_users.id'], name='a_users_tags_userId_fk', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('a_users_tags')
    op.drop_table('a_users_roles')
    op.drop_table('a_users')
    op.drop_table('config_tags')
    op.drop_table('config_role_has_permissions')
    op.drop_table('co_addresses')
    op.drop_table('config_tag_types')
    op.drop_table('config_roles')
    op.drop_table('config_permissions')
    op.drop_table('co_languages')
    op.drop_table('co_countries')
    # ### end Alembic commands ###
